### ISSUE TITLE
Rearrange the folder structure of the repository

### ISSUE THREAD

**Issue by cmiller8** [buds-lab/ashrae-great-energy-predictor-3-overview-analysis#15]
The folder structure doesn't make sense anymore in the context of the paper -- would be great to rearrange the folder to match the paper

![image](https://user-images.githubusercontent.com/193675/75772637-494d6b00-5d87-11ea-8d7e-b1c1bf3a9f6a.png)

**Comment by cmiller8** [comment]
Hi @PatrickFu0302 -- can you work on this -- it makes sense now to change the folders and the documentation from "Section X" to just signify the data processing category ie: "Demographics", "Discussion Board", etc.

**Comment by PatrickFu0302** [comment]
Done.
