### ISSUE TITLE
Create a directory on a wiki page of the solutions 

### ISSUE THREAD

**Issue by cmiller8** [buds-lab/ashrae-great-energy-predictor-3-overview-analysis#21]
Create a wiki page that has all of the solutions from the paper:

![image](https://user-images.githubusercontent.com/193675/82746044-fdc2c000-9dbd-11ea-989c-afa42b39b005.png)

Seems like all the information is here: https://docs.google.com/spreadsheets/d/1HZz-tM1TomXYz2Ux0dNXfU7sF4_yrnAEAXtLoLYUnMs/edit?usp=sharing

**Comment by PatrickFu0302** [comment]
Done.
Check here: https://github.com/buds-lab/ashrae-great-energy-predictor-3-overview-analysis/wiki/Shared-solutions-in-kernel-notebooks-and-discussion-board
