### ISSUE TITLE
Change the Figure 1 to address the reviewer suggestion

### ISSUE THREAD

**Issue by cmiller8** [buds-lab/ashrae-great-energy-predictor-3-overview-analysis#22]
![image](https://user-images.githubusercontent.com/193675/82800289-0abedc80-9eae-11ea-92e0-11b54d60aa25.png)

And the review comment that needs to easily be fixed on this graphic:

![image](https://user-images.githubusercontent.com/193675/82800342-1f02d980-9eae-11ea-92b1-616494df1e6e.png)

**Comment by PatrickFu0302** [comment]
Done.
https://github.com/buds-lab/ashrae-great-energy-predictor-3-overview-analysis/blob/master/KernelNotebook/graph/meta_summary(Fig1).pdf

**Comment by cmiller8** [comment]
thanks!
