### ISSUE TITLE
Discussion Scraping fails to scrape all available pages 

### ISSUE THREAD

**Issue by anjukan** [buds-lab/ashrae-great-energy-predictor-3-overview-analysis#5]
Scraping notebook fails to scrape all available pages for discussions. Currently fails on page 7 of search when more pages are available.

**Comment by cmiller8** [comment]
@anjukan -- did you get this figured out? If so, go ahead and close the issue

**Comment by cmiller8** [comment]
@anjukan -- can you help close this issue if its not an issue anymore? :)
